---
title: "TETS"
output: html_document
---

#CHECKING NA VALUES
```{r}
is_na_check_m <- morphology_raw %>% is.na
is_na_check_m <- tibble(is_na_check_m)
is_na_check_m %>% distinct()


is_na_check_exp <- expression_raw %>% is.na
is_na_check_exp <- tibble(is_na_check_m)
is_na_check_exp %>% distinct()

```
###Scatterplot and boxplot for each attribute vs sex (error vs population)

#premass
```{r}
pl1 <- final_data %>% ggplot(mapping = aes(x = premass,
                                           y = ID,
                                           color = Sex)) + 
  theme(axis.text.y = element_text(size = 5)) +
  geom_point()

pl2 <- final_data %>% ggplot(mapping = aes(x = Sex,
                                           y = premass)) + 
  geom_boxplot()

pl3 <- final_data %>% ggplot(mapping = aes(x = Population,
                                           y = premass)) +
  geom_boxplot()

show(pl1+pl2+pl3)

```
#postmass
```{r}
pl1 <- final_data %>% ggplot(mapping = aes(x = postmass,
                                           y = ID,
                                           color = Sex)) + 
  theme(axis.text.y = element_text(size = 5)) +
  geom_point()

pl2 <- final_data %>% ggplot(mapping = aes(x = Sex,
                                           y = postmass)) + 
  geom_boxplot()

pl3 <- final_data %>% ggplot(mapping = aes(x = Population,
                                           y = postmass)) +
  geom_boxplot()

show(pl1+pl2+pl3)
```

#weightloss  !!POTENTIALLY OUTLIERS
```{r}
pl1 <- final_data %>% ggplot(mapping = aes(x = weightloss,
                                           y = ID,
                                           color = Sex)) + 
  theme(axis.text.y = element_text(size = 5)) +
  geom_point()

pl2 <- final_data %>% ggplot(mapping = aes(x = Sex,
                                           y = weightloss)) + 
  geom_boxplot()

pl3 <- final_data %>% ggplot(mapping = aes(x = Population,
                                           y = weightloss)) +
  geom_boxplot()

show(pl1+pl2+pl3)
```
#TIME.SEC !POTENTIALLY OUTLIERS
```{r}
pl1 <- final_data %>% ggplot(mapping = aes(x = time.sec,
                                           y = ID,
                                           color = Sex)) + 
  theme(axis.text.y = element_text(size = 5)) +
  geom_point()

pl2 <- final_data %>% ggplot(mapping = aes(x = Sex,
                                           y = time.sec)) + 
  geom_boxplot()

pl3 <- final_data %>% ggplot(mapping = aes(x = Population,
                                           y = time.sec)) +
  geom_boxplot()

show(pl1+pl2+pl3)
```

#DISTANCE !!POTENTIALLY OUTLIERS
```{r}
pl1 <- final_data %>% ggplot(mapping = aes(x = distance,
                                           y = ID,
                                           color = Sex)) + 
  theme(axis.text.y = element_text(size = 5)) +
  geom_point()

pl2 <- final_data %>% ggplot(mapping = aes(x = Sex,
                                           y = distance)) + 
  geom_boxplot()

pl3 <- final_data %>% ggplot(mapping = aes(x = Population,
                                           y = distance)) +
  geom_boxplot()

show(pl1+pl2+pl3)
```

#averagevelocity !!POTENTIALLY OUTLIERS
```{r}
pl1 <- final_data %>% ggplot(mapping = aes(x = averagevelocity,
                                           y = ID,
                                           color = Sex)) + 
  theme(axis.text.y = element_text(size = 5)) +
  geom_point()


pl2 <- final_data %>% ggplot(mapping = aes(x = Sex,
                                           y = averagevelocity)) + 
  geom_boxplot()

pl3 <- final_data %>% ggplot(mapping = aes(x = Population,
                                           y = averagevelocity)) +
  geom_boxplot()


show(pl1+pl2+pl3)
```

#maxvelocity 
```{r}
pl1 <- final_data %>% ggplot(mapping = aes(x = maxvelocity,
                                           y = ID,
                                           color = Sex)) + 
  theme(axis.text.y = element_text(size = 5)) +
  geom_point()

pl2 <- final_data %>% ggplot(mapping = aes(x = Sex,
                                           y = maxvelocity)) + 
  geom_boxplot()

pl3 <- final_data %>% ggplot(mapping = aes(x = Population,
                                           y = maxvelocity)) +
  geom_boxplot()

show(pl1+pl2+pl3)
```

#power !!POTENTIALLY OUTLIERS
```{r}
pl1 <- final_data %>% ggplot(mapping = aes(x = power,
                                           y = ID,
                                           color = Sex)) + 
  theme(axis.text.y = element_text(size = 5)) +
  geom_point()

pl2 <- final_data %>% ggplot(mapping = aes(x = Sex,
                                           y = power)) + 
  geom_boxplot()

pl3 <- final_data %>% ggplot(mapping = aes(x = Population,
                                           y = power)) +
  geom_boxplot()

show(pl1+pl2+pl3)
```

#area !!POTENTIALLY OUTLIERS
```{r}
pl1 <- final_data %>% ggplot(mapping = aes(x = Area,
                                           y = ID,
                                           color = Sex)) + 
  theme(axis.text.y = element_text(size = 5)) +
  geom_point()

pl2 <- final_data %>% ggplot(mapping = aes(x = Sex,
                                           y = Area)) + 
  geom_boxplot()
pl3 <- final_data %>% ggplot(mapping = aes(x = Population,
                                           y = Area)) +
  geom_boxplot()

show(pl1+pl2+pl3)
```

#mean
```{r}
final_data %>%
  select(where(is.numeric)) %>%
  summarise(across(everything(), mean))  
```
#standard deviation
```{r}
final_data %>%
  select(where(is.numeric)) %>% 
  summarise(across(everything(), sd))
```

#max
```{r}
final_data %>%
  select(where(is.numeric)) %>%
  summary() 
```
#min
```{r}
final_data %>%
  select(where(is.numeric)) %>% 
  summarise(across(everything(), min))
```
#var
```{r}
final_data %>%
  select(where(is.numeric)) %>% 
  summarise(across(everything(), var))
```



