---
title: "PCA"
output: html_document
date: '2022-04-28'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#Data loading
```{r}
data <- read_tsv(file = "data/03_my_data_clean_aug.tsv",show_col_types = FALSE)
```

#Data preprocessing for PCA
```{r}
PCA_data <- data %>% 
  select(where(is.numeric),
        -(matches("energy|
                  Log|
                  eff|
                  PC|
                  time.sec|
                  power")))

as_tibble(PCA_data)
```

#PCA
```{r}
pca_fit <- PCA_data %>% 
  prcomp(scale = TRUE)
```

#PC1 VS PC2 Plot
```{r}
pca_fit %>%
  augment(data) %>% # add original dataset back in
  ggplot(aes(.fittedPC1, .fittedPC2)) + 
  geom_point(size = 1.5) +
  scale_color_manual(
    values = c(malignant = "#D55E00", benign = "#0072B2")
  )
```
#Eigenvalues percentage
```{r}
pca_fit %>%
  tidy(matrix = "eigenvalues")
```

#Eigenvalues percentage plot
```{r}
pca_fit %>%
  tidy(matrix = "eigenvalues") %>%
  ggplot(aes(PC, percent)) +
  geom_col(fill = "#56B4E9", alpha = 0.8) +
  scale_x_continuous(breaks = 1:9) +
  scale_y_continuous(
    labels = scales::percent_format(),
    expand = expansion(mult = c(0, 0.01))
  ) 
```

#Rotation matrix
```{r}
pca_fit %>%
  tidy(matrix = "rotation")
```

#Plot rotation matrix(arrows)
```{r}
# define arrow style for plotting
arrow_style <- arrow(
  angle = 20, ends = "first", type = "closed", length = grid::unit(8, "pt")
)

# plot rotation matrix
pca_fit %>%
  tidy(matrix = "rotation") %>%
  pivot_wider(names_from = "PC", names_prefix = "PC", values_from = "value") %>%
  ggplot(aes(PC1, PC2)) +
  geom_segment(xend = 0, yend = 0, arrow = arrow_style) +
  geom_text(
    aes(label = column),
    hjust = 1, nudge_x = -0.02, 
    color = "#904C2F"
  ) +
  xlim(-1.25, .5) + ylim(-.5, 1) +
  coord_fixed()  # fix aspect ratio to 1:1
 
```

